### PR TITLE
Remove references to added & configured

### PR DESCRIPTION
**Pull request by elsmr**

### CODE REVIEW

**Review by GeertWille — APPROVED** [review]

**Comment by elsmr** [comment]
One sec, noticed 1 issue with deleting connections

**Comment by Gdewilde** [comment]
#### 📝Changed routes:


| [**…nified-api\]/\[provider\]**](https://integration-settings-fbkem0sii-apideck.vercel.app/integrations/[unified-api]/[provider]) |
|:-:|
|<a href="https://integration-settings-fbkem0sii-apideck.vercel.app/integrations/[unified-api]/[provider]">Screenshot of /integrations/[unified-api]/[provider]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/VLPv0en8xLs3WAdRGxM11jxLdJ_9GcWFZtYSJC4mfRSQVsHdU9Qyy3Za4WaCtmAqxLxie8mhloJzgM8efI8gXA.png">(view full size)</a> |







Commit 94491fb4c733a8b9c17b82859b3fa9e2b900c6a4 (https://integration-settings-fbkem0sii-apideck.vercel.app).

**Comment by Gdewilde** [comment]
Can be merged?

**Comment by elsmr** [comment]
yes good to go

**Pull request merged**
