### PR TITLE
Add error alert when OAuth flow fails

### PR DESCRIPTION
**Pull request by elsmr**
unify: https://github.com/apideck-io/unify/pull/764

### CODE REVIEW

**Review by jakeprins — APPROVED** [review]
Nice work!

**Comment by Gdewilde** [comment]
@elsmr time to go over it together?

**Comment by Gdewilde** [comment]
@elsmr good to go?

**Comment by elsmr** [comment]
Ready now, added some GitHub Actions :smile:, OK for you @jakeprins ?

**Comment by jakeprins** [comment]
> Ready now, added some GitHub Actions 😄, OK for you @jakeprins ?

Nice!

**Pull request merged**
